//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagerment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Account
    {
        public int ID { get; set; }

        [Display(Name = "Tên ğãng nhâòp")]
        [Required(ErrorMessage = "Baòn chıa nhâòp tên ğãng nhâòp !!!")]
        public string TenDangNhap { get; set; }

        [Display(Name = "Mâòt khâÒu")]
        [Required(ErrorMessage = "Baòn chıa nhâòp mâòt khâÒu !!!")]
        public string MatKhau { get; set; }

        public int Level { get; set; }
    }
}
