//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagerment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.NhanVien_ThietBi = new HashSet<NhanVien_ThietBi>();
        }

        [Display(Name = "STT")]
        public int ID { get; set; }

        [Display(Name = "Tên nhân viên")]
        [Required(ErrorMessage = "Baòn chýa nhâòp tên nhân viên !!!")]
        public string TenNhanVien { get; set; }

        public string Email { get; set; }

        [Display(Name = "Sôì ðiêòn thoaòi")]
        [Required(ErrorMessage = "Baòn chýa nhâòp sôì ðiêòn thoaòi !!!")]
        public int SoDienThoai { get; set; }

        [Display(Name = "Ðiòa chiÒ")]
        [Required(ErrorMessage = "Baòn chýa nhâòp ðiòa chiÒ !!!")]
        public string DiaChi { get; set; }

        [Display(Name = "MaÞ nhân viên")]
        [Required(ErrorMessage = "Baòn chýa nhâòp maÞ nhân viên !!!")]
        public int MaNhanVien { get; set; }

        [Display(Name = "AÒnh")]
        public string Avatar { get; set; }

        [Display(Name = "Traòng thaìi")]
        public Nullable<int> Status { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<int> Zoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien_ThietBi> NhanVien_ThietBi { get; set; }
    }
}
