//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagerment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhanVien_ThietBi
    {
        [Display(Name = "MaŞ hôÌ sõ")]
        public int ID { get; set; }

        [Display(Name = "MaŞ nhân viên")]
        [Required(ErrorMessage = "Baòn chıa nhâòp maŞ nhân viên !!!")]
        public int IDnhanvien { get; set; }

        [Display(Name = "MaŞ thiêìt biò")]
        [Required(ErrorMessage = "Baòn chıa nhâòp maŞ thiêìt biò !!!")]
        public int IDthietbi { get; set; }

        [Display(Name = "NgaÌy mıõòn")]
        [Required(ErrorMessage = "Baòn chıa nhâòp ngaÌy nıõòn thiêìt biò !!!")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime NgayMuon { get; set; }

        [Display(Name = "Traòng thaìi")]
        public int Status { get; set; }

        [Display(Name = "Ghi chuì")]
        public string ThongTinMoTa { get; set; }

        [Display(Name = "NgaÌy traÒ")]
        [Required(ErrorMessage = "Baòn chıa nhâòp ngaÌy traÒ thiêìt biò !!!")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> NgayTra { get; set; }

        public virtual NhanVien NhanVien { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
