//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquipmentManagerment.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ThietBi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThietBi()
        {
            this.NhanVien_ThietBi = new HashSet<NhanVien_ThietBi>();
        }

        [Display(Name = "MaÞ thiêìt biò")]
        public int ID { get; set; }

        [Display(Name = "Tên thiêìt biò")]
        [Required(ErrorMessage = "Baòn chýa nhâòp tên thiêìt biò !!!")]
        public string TenThietBi { get; set; }
        public string Model { get; set; }

        [Display(Name = "Thông tin thiêìt biò")]
        public string Thongtin { get; set; }

        [Display(Name = "Traòng thaìi")]
        public Nullable<int> Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien_ThietBi> NhanVien_ThietBi { get; set; }
    }
}
